version: '3.7'
services:
  app:
    image: nginx:alpine
    networks:
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.port=80'
      - "traefik.frontend.rule=Host:meuapp.localhost"

networks:
  proxy:
    name: infra_proxy
    external: true

